POST https://phonebook-backend-hgef.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Bill Gates",
    "number": "080-7654321"
}

###
POST https://phonebook-backend-hgef.onrender.com/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "080-7654321"
}

###
POST https://phonebook-backend-hgef.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": ""
}

###
POST https://phonebook-backend-hgef.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "080-7654321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bi",
    "number": "080-765432"
}
