GET https://phonebook-backend-hgef.onrender.com/api/persons

###
GET https://phonebook-backend-hgef.onrender.com/info

###
GET https://phonebook-backend-hgef.onrender.com/api/persons/1

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/65eb01176b783ed71d0b358d